language: node_js
sudo: false
node_js: '0.11'
before_install:
- npm install
- npm install -g bower && bower install
addons:
  sauce_connect: true
before_deploy: bash ./ci/build_release.sh
deploy:
- provider: releases
  api_key:
    secure: UyTYLCcdkf+F3VlEIRYm/hBwPGRfN1cA+HfjG4qLsYjLLb67xyXuekDo9fVz6QdZq/lTJY5nzuk8G2Wnah4XbuXyWd9p7Mtvv2mT0GlHgCFjm2hsVk22d1qCVl0ZJEllNs9NWzDSPr5bLjz9HUvUqKcH8CNnZW98exJLwACN7OhO5Q9Rwt6jiVwLe2Rn5IDf4Nro1PExuU2y1vAfqnWRYc6GNWdR8mVdf6gzUXZUOLD6+hWRRY3GOnv5xQTp440JqF1D3L52pdy5Ua5HodO6S+kU1QAOyCeXpTAdS/mP99ehNr+RnXhi+nxCfInqstQ5WQBt3WED5MIdx2XBydyQaKT+tqYAH7Ike2koRcYeLkeBLnC3TebiRawQKCcixZnl0TNd2jQGVySrDr0CfeJ5OyDyFs+HRwvh9hhNLhL2zbJx+AMu+REfliGOpMMCwBtgB0WeHZFwxVQcseS6rGSW1inZnR/DcB0ova3HloI1TMigwUvOZsg02UYy+rEGFystBnQH8Yo64fZEQ4APJWPBSuONG1F3ywcvpvlx2wZ0xlo2fohm+5xw3zWnIrU2Gkv3F2H36CJAhYatLqu6HU4T3vtICG8md07Y+EBjvgiSKTTizPq9bxddh+6WPwom1tH70H3qT7/X99A5YqX8l/DGerLh23lxMX1LP1NXdpwmvdM=
  file:
  - dist.tar.gz
  - dist.zip
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: ci/update_pages.sh
  skip_cleanup: true
  on:
    branch: master
cache:
  directories:
  - node_modules
  - bower_components
env:
  global:
  - NODE_ENV=travis
  - secure: kQE+nA/FOSWs9/5dXB0fMEBvLTsDPsUY00e3a4Ni/DhNr5E6jfeaUH8ejbC39+fBry2T/gRFF+LhlZbB0PCIEpvxzOkJeMRb+A9Du8JHh+M7MXj7x9Wg/2Noi7z+szPouxMRAHow6dzkk6DRviEm3Ew5Hew2yaVZu9dse/qK6c6U94uStoWTQVvhPulWvtmJFMjgcoqHCK76YzFhW1HrmOCrBmseH4xpheaKyeOp2TXnIvfvWGtQ0Tq755p6KYT4S87t+Mn4eUa8VCGPq/o2SI+SOlYpzTqD16TXtqiI3BXx2Fczr5bw+WMdQlqhApGVAjP7l/F1IVrU9C6E1uaJQ7UBcCUuy4pCzjmSFdyJyvgupEYApeDmGq7gvTzym+Hgc1NAXqsOIbayIrjxvwVt2wh1KUnX16gcE/hMoxBOC2A5U5ydd9vnhSiwAh1Ed1EEVLj7SfmJ8Nwb51jrYfEm/q5LJyItbVtlpJPbzZZ5w3AtezPGDsmqCddmhvbnPUuaKo3Hrp8vjS6K3KM0IFFFvcAcsVCcrNUd6lWuJ7hcCODmBrfsAyw2Zsd82JG+V//dQtzMoc/FX+oaUexudPrk4E6hfYDvU+gyV0fb2FEHkx53SDmmQwFEf4gAO9tCn6kBJkngZgbzo+s2aMhGpHc7vX2zX5mc6bBTlZngBP4iK8Q=
  - secure: GLhurlKQrMXS4z+NFQ3sZLcr+1+tQSKOMk/xVikGTComru+pyqW3ir+q+JAgQFvRgnQdQEVsZioQ+puzZb3tPFSPWOdFupiFYJ9tbamUJkXtge2XLRW7/K5Qn+u0ZRjqi9dDV6uCnWCeE34pKApUEvf4eek69Z7SiqHolT76vFMH0NV0kdRZehB/HZi/Fd2pDyFJlaoJiA2pmHVMuy7SINlmeMdEziQFpJ2hZbNe/2X2xQdGR6u/gBhOa+wQA6VDWQwXJCwc7VV84qQKx1hL0kVwmRMPvUL0h5W1R9zgMuzLKTWeTUfdWPMK4u0bOtKm/Et2BmF9rzE2YjStudcDv6lpazYpxITo747aD5+OwXyIT4RGKEXChScpgYDhxECMPUpjDBMAvaOEuynDJCTJiL1OfIAhzIwTAUBx+VqcFPsuwS6OYCxjy0xxSnywE0xeDynw1ApM/Mir4XtGuszNARrInnwXifaUJhXgUH/8dAHE+mslkb5cUKGFSYa6Q/Js2V6NfdUCK32SaYsm41CqYE9mMAwVSpseEZlBr5KN6xxmxoFgNXvo53Td2Ml1ly2Kxdhz3l4xl2kQWWu9XMqLi4NcDsjOSsijt7Wi8pRtji7PIjbpubw0H3q8Gg/PVl4xhzUQ0rhHdE+pNkfnjHpDKlXzAGP/Cgdz1bFwf6WlE10=
  - secure: MMa00Mi8rkHcJH8W6glwDDXcfP89xAyijPj15JDv4eKd5EqgJre7tZ2YqwhysUBu769+TdZJmHelQv7DwHmZxgi06nzFTSGAGJ8n4XwAoODTSu184ZCiGFGoa30SciZowFci9ssmRLB1+qYqNDXDGvdh9GEIO2ep18bfmEetB4Gq5mkdBZMZwdfuJGjtk2i/y2nCLnPpWlUefFS7bETu3TdeH/fhz7Y1VzDsFzTRb/59d4EwwIc08O3sHOJX3o42R+BqaxIyR5E+zI9Xz6YuVUpyuhcuq72dqvO64mSwmdZLvjys2YrvgxstfjjccoRcq4mi/HwyYo+auv1IEVmQE++5NrKyeJW15wwAIkYrd+YCWHijd8tTcGrQAfFgotVvPu3FC8/URHkkPuRLM4joBi4a9u6PVwyRoSrA6lXHcHXLGWLmkTdKqoOF+kHS+wIdFXwmSg7Jjeejt/X0DGihBqYic0oiw3SyI5oYKVhGmutjYtG2yXYtdHUGcXb5V/LAIU4wWi3OW4MSxRSgVhdSJl7CyCQUVDiu921rLtJI7gzcDrHEWoi2U7uUjF4cTVf3lKN93tlY6LJVZTIKBK8wqzKbrpDLlLzCo0xxC7sLc36sW+1PTVKDdI649673XCEOt/hcd20jQk+BnCwPqTQL886QQJtWiwmZZIEHbVEiJGQ=
