language: node_js
sudo: false
node_js: '4'
branches:
  except:
    - edge
    - releases
    - gh-pages
    - no-tracking-release
addons:
  sauce_connect: true
before_deploy: bash ./ci/build_release.sh
deploy:
- provider: releases
  api_key:
    secure: I3E0Gj7DkMrw8dwq/nUej4LxE7q/u27Vcy+GUM2tyaL6/3OgzWF0WOOxu7O7IzMVg0+Mp2bNP4GDxUGxs5n34wTQBHgWAnZ3eUoINPQuWLGLrSHRuNMhGYYi5GsMbFle+dAvMD8B8E6+o+zRW3NLj3BxU35LedYMdy93QDhWv8yshyGCYyTWbzni/5RZ/2m1UBoD5+bgbkMX2KCcq2F/WgsbcIezIIpmmhR/PpZvk8hInsLngZpv4A/Yjm634XtbBdrxHoTrDG7+W5VV3KRd+vADLPoj6xmL+6IjCj8w0C9nD6fpeA2m29UzkWyjVHmvESLNOZFPW3z269/GgjJuLrlxvNJcAwlf7cb+LfTfr/XNfwwhkU98CJ36HlODHSlsTVkp185sCFdOueWrmAtxyiR/l/4HycO5CFVMlHeTwsvOeUT53Qm5k0hsxMPTry6NfA6mjhmg+19CZ1ebC9/GrqjKItujt/RdBIKOj/3kHUSgnpCK2X/l/xEDiyZsh5uDuQd9msP6QH9DtSaUYTOnKrXQ0IqdQ5rV1k3PlAkjtxeTOz2AREjJ5H6LuHmH5uMlcyLtuDomUswL9J2rnD/nb8TUp0kSaUsArM47rd1lYjfRlYAvnLhTAQXGl713zt6X9veh1OLn6DZubgwO/7yJ//GsPSwcjzttbO0JlheUZ5k=
  file:
  - dist.tar.gz
  - dist.zip
  skip_cleanup: true
  on:
    repo: ufal/lindat-common
    all_branches: true
    condition: '-n "$TRAVIS_TAG"'
- provider: npm
  email: sedlakmichal@gmail.com
  api_key:
    secure: EpHOw9dFoYggHLQCgNLL04QBEPaHN7jYvpS/laZC1n02lZ+4HMUYhhXtwNF6lwhz0e9W9nEGsk2P8k8xwz0P1i7f5pGVGZG0sN3spevmsmb9jd824o5UV2cLcDrf8QsQn/c8S57Hyi27avqr2weYmnFyLPIaGvH1VzbdbShztJai2KmLeTF596DseNQaHIdjjRzyjr5FKeJqNiGXKzAyNPVTtenMVSEe+51tnVQ+jomGAc/v1iR5JwCY2x9svvdtxpP1ImL5SMA/WHItMptoz33E7+wC2lcCQOXcGad+rsOPFZrA+H4NNiImKvFFC4UfdDz0ajQZCKdrFn+2SbfhJ2dxoewByddut2svDVm2eh108TW/CvwKkNKkkc37uZ7WRLl9k7fOHtq3tg5E72zvGJbKqxaZJPS1TGveyZI9fAuXRwH9aBC5prHoTDpAXHL4os5+0j+2rcUIQGrrQkJXN/pQl6hdqk3L31PpWi6HcrZ4lQzkqI3Bdxr39usgYe8IkSqbjjcIUFjccqKwJysNm4RUDCVGIiDhZ55+Pb02LhQrh/8E2DrR1f6Td/f39oKvdzEHHwuSsrPNWTBklG71iPbm9ED3l030kYoZD9YrIIUguVXPTtNM+42alpoF36aVvZjITpCbDNlzkvfYo7gmWKm7fupfaPow+BAUyOwnD3k=
  on:
    repo: ufal/lindat-common
    all_branches: true
    condition: '-n "$TRAVIS_TAG"'
- provider: script
  script: bash ./ci/push_build.sh
  skip_cleanup: true
  on:
    repo: ufal/lindat-common
    all_branches: true
    condition: '-n "$TRAVIS_TAG" || "$TRAVIS_BRANCH" = "master"'
cache:
  directories:
  - node_modules
  - bower_components
env:
  global:
  - NODE_ENV=travis
  - secure: AQCTw6esLb/qn13MtYmcrGAFCtDa8x7mB8dW0+KFTjIUdeOyRPhDpmsP8rEJupLL6q6IH+Zr+IMbe/1bVR6JmEAcgnj/5on03vqp0m+YxSQzIrhKX5Uy69ZBcx1jy6TdXRNlemlxd5AtgzOeM+yGEq2Ey8xlDzGv1ZeVLYt8xDbTpBY8sQyh0xKGR6Zkv7vOU4AjNqeK0VIdG1en6VRTXeD4TVCrH+EVuFAhbIXNrptieOTxJ+Cmhsbu30YuUyIlnijDh25+VqWo5rFrjBjbubHjkq74gWJyGcd5H8IKWqfkbLEAtIBYxMF+NLxPvrndX3jEO8YSIjC9XTVRD9d9Krs+obCx+eu51HMIgcEW8xpamxJc7FraU0G3b7NkWVhpPwrGfM0bNcA9HZ6B21AJE3X1wiFK7gcPJTxvUo7IVYUtnqUHYwPjpB3mdYznOSudFhPdtKgD/IbVW9l60bCalI+8q76Lhr2sLCD25PAFDIW6E6Fwxzijgz3RGrVlsqohYgb7vScY0HZNfvcZj1A8YG0JASGHAZIAP/VMhzpik2E6nBnXtrjvTb/LXVx10FeTUgPgQ79KzXxq7CUruWMT6AL412e8nIJXJrMdOZvsDBkYVv8guOEE/vRp5oSqHnV8jUeTLpHNIroZd910O9KRwo2BN88uo/M0VxXU/jP8G5k=
  - secure: k/sF+S9tEwlNpLgi9DO4Y9MA3cuifIi1TEDcxPR/69MtvIJPF21ty9W3+H4ZwjyeZy4oXrgAQwWNUO127GkSOmUPWpMKYN48YrhGmUGSVRcvXndMm2F2fC2I+WCjTuJxBZJmdBi3W/8LUrAkKTFHHFEgQ1pG7XQM3natKmtx0RKda5+YX0tpky7rczkMSECJ+1vGYoir3nQh4cLGlkqUepNPP5lo/G7ZVPeTFXNgTFWWo9ec5fU/B5PZSz6A0LKgzHsPceWcvcJar9Xtn6vyBD3WdIokYuW868CXDs0gukQuHr+H4ENvLx3rFdlJV4nLVU90cKAMd9qBmVvqjOKJeGf9Lyykdr4Cgh0kacGtvs/bwFRxrQql+bvOigZlegHIeAwGMU3zo2rVFGKEX7mrtslkOf316IjfmEFi7RShiSG3HI/2U73aM8iXzC3cmw601aQpeZ3hvCdsIgc7DaISwJVSWkJL22R+J3a1oDJPTr3j6Sy7yltkKKJZYzGipjC5huWGVmhpUUHizglMb4/T4oxy3Zc67RdWOfVZlndp/0GmKA0M2W/FEUMUTxgaEOx4HVfEHt5hrJ+Lxrxmng0dI1UhvqD+hhkoyNBrpZ2txf1thWuy5HxylOmqB2XObOLl6rOsmR+BiO9BE02tStCegkZ3YlbEhtzWJuEhi6h4/yY=
  - secure: mZyuPjduDBZO/SdRrjCDjKEiOJZb0Xb1drxW6EF+c7RFBO/UyOY/kD4G+pZQdVmt7z8F119wzVEziPaiGAhUWyHgQyr8sjlwMw20D/9C19JLANTvWdawsW6BH0NZ0hB1WVROgPA8LXfB06g11tnQfIkwyfQE+qNZH4LWJ5+lUh3DgQBpFGHKBw/WFTIPSLw1yJj54PQRlqvrt4aCRwkI/kT+bG4IDWQojWUu5n/hcfjpqr1SxgLwivWtawP7RaUdqX3DOdLJa4vGUUSkqx8jLDGWxmUxzyZpezkoLdHVPp1YaBIoeXTzs4wlifDyFYcIcuoVz9FevCwXOlJju8Tje+zB7N6BnzCNzY+0fFz5DH9+1MTxkaNknNJqqJVqQzlDmPKbltIEMHLRSGNNyn/8l+JaR0xrdwPK/QfY3mIbWeBCv2jEDMdHgZtRQ89r8Hmh9WxzaCFml8nOUHL89NJJ4m7JG7bdRVI71GVGx5eUJbSRgY/XIkL0YQXih2vaWiIIw7ZAysxmxGnpnBoEthreUmge5iXeS65kozPEIuBko2jn2mDZwF8tY/xW6wRDWQKwmIfET9slRU5CTqCWoBMFa/H2eFpjLzYcsWyY4tfUhTCDjR3g3KQMU1LsH03GAY+8Vg1kVANKrqSNJKOJNIRrJABHw+PwkneXZn1uE5sVlQk=
