language: node_js
sudo: false
node_js: '12'
branches:
  except:
  - edge
  - releases
  - gh-pages
  - no-tracking-release
addons:
  sauce_connect: true
before_deploy: bash ./ci/build_release.sh
deploy:
- provider: releases
  api_key:
    secure: KAmHutneL86jsZmuSZEDoG+XsSYNt4FPpY+uEyoADcm6+Tzr09cmwbccwA+yokSv3sSXA/iNwatTOymJr4eBb99mx/6yX244pc3IffauZ1FJOW5xBOzxUp/OmQl488E89dz54nun2Inso/D6Kdlwenyyks64t2MCUK/giJXI1QP0MoyrGCrWz5FFZDpkniEDfZzMPLOmoq/854XydcjnsxOQ/UC6L0FNqrXA8P+/ZckuNEYmq/x/2+xqI/m9MtCAbdRsxpnhQhHwG4m6OgNUdnHvAqQRgzSh6R6fQw4eUFT6qA4waggeaAYcQyd2H4UQKtOy0rYVuBFKcmWVNf+oMeRgVvK6f2bFOn6yqOQhPr0rpBL02T1OyoiGuEmuXfKdgJA5W5I2976HZAzUPx5Fx9FhnsruVu4FyXkKCAZdjgWjchXYx7ApCh1Rs+b/obU6s8+bA3JQhmhcDJDKqjIYsPdPKfBB8phTQ8LovdXQxkJDT0ZBHD7VW8OvmTnGkJLzCeZrikpb/mQhnOo5Be4abBAmwO6faykVmOaBqJtRKM64Wi0bd1JEk/mxYW7JK620QzbgsPshdjzifyIJ0WdTCFFy0iCOoJzlNHS+3gS6oVV4JnwfJOwClCQf5XQfoJnBeW9nQgI33ckk5FapamOAmHRoHbB/1GwB+ErIU7iEYVA=
  file:
  - dist.tar.gz
  - dist.zip
  skip_cleanup: true
  on:
    repo: ufal/lindat-common
    all_branches: true
    condition: -n "$TRAVIS_TAG"
- provider: npm
  email: lindat-technical@ufal.mff.cuni.cz
  api_key:
    secure: EpHOw9dFoYggHLQCgNLL04QBEPaHN7jYvpS/laZC1n02lZ+4HMUYhhXtwNF6lwhz0e9W9nEGsk2P8k8xwz0P1i7f5pGVGZG0sN3spevmsmb9jd824o5UV2cLcDrf8QsQn/c8S57Hyi27avqr2weYmnFyLPIaGvH1VzbdbShztJai2KmLeTF596DseNQaHIdjjRzyjr5FKeJqNiGXKzAyNPVTtenMVSEe+51tnVQ+jomGAc/v1iR5JwCY2x9svvdtxpP1ImL5SMA/WHItMptoz33E7+wC2lcCQOXcGad+rsOPFZrA+H4NNiImKvFFC4UfdDz0ajQZCKdrFn+2SbfhJ2dxoewByddut2svDVm2eh108TW/CvwKkNKkkc37uZ7WRLl9k7fOHtq3tg5E72zvGJbKqxaZJPS1TGveyZI9fAuXRwH9aBC5prHoTDpAXHL4os5+0j+2rcUIQGrrQkJXN/pQl6hdqk3L31PpWi6HcrZ4lQzkqI3Bdxr39usgYe8IkSqbjjcIUFjccqKwJysNm4RUDCVGIiDhZ55+Pb02LhQrh/8E2DrR1f6Td/f39oKvdzEHHwuSsrPNWTBklG71iPbm9ED3l030kYoZD9YrIIUguVXPTtNM+42alpoF36aVvZjITpCbDNlzkvfYo7gmWKm7fupfaPow+BAUyOwnD3k=
  on:
    repo: ufal/lindat-common
    all_branches: true
    condition: -n "$TRAVIS_TAG"
- provider: script
  script: bash ./ci/push_build.sh
  skip_cleanup: true
  on:
    repo: ufal/lindat-common
    all_branches: true
    condition: -n "$TRAVIS_TAG" || "$TRAVIS_BRANCH" = "master"
cache:
  directories:
  - node_modules
  - bower_components
env:
  global:
  - secure: AQCTw6esLb/qn13MtYmcrGAFCtDa8x7mB8dW0+KFTjIUdeOyRPhDpmsP8rEJupLL6q6IH+Zr+IMbe/1bVR6JmEAcgnj/5on03vqp0m+YxSQzIrhKX5Uy69ZBcx1jy6TdXRNlemlxd5AtgzOeM+yGEq2Ey8xlDzGv1ZeVLYt8xDbTpBY8sQyh0xKGR6Zkv7vOU4AjNqeK0VIdG1en6VRTXeD4TVCrH+EVuFAhbIXNrptieOTxJ+Cmhsbu30YuUyIlnijDh25+VqWo5rFrjBjbubHjkq74gWJyGcd5H8IKWqfkbLEAtIBYxMF+NLxPvrndX3jEO8YSIjC9XTVRD9d9Krs+obCx+eu51HMIgcEW8xpamxJc7FraU0G3b7NkWVhpPwrGfM0bNcA9HZ6B21AJE3X1wiFK7gcPJTxvUo7IVYUtnqUHYwPjpB3mdYznOSudFhPdtKgD/IbVW9l60bCalI+8q76Lhr2sLCD25PAFDIW6E6Fwxzijgz3RGrVlsqohYgb7vScY0HZNfvcZj1A8YG0JASGHAZIAP/VMhzpik2E6nBnXtrjvTb/LXVx10FeTUgPgQ79KzXxq7CUruWMT6AL412e8nIJXJrMdOZvsDBkYVv8guOEE/vRp5oSqHnV8jUeTLpHNIroZd910O9KRwo2BN88uo/M0VxXU/jP8G5k=
  - secure: k/sF+S9tEwlNpLgi9DO4Y9MA3cuifIi1TEDcxPR/69MtvIJPF21ty9W3+H4ZwjyeZy4oXrgAQwWNUO127GkSOmUPWpMKYN48YrhGmUGSVRcvXndMm2F2fC2I+WCjTuJxBZJmdBi3W/8LUrAkKTFHHFEgQ1pG7XQM3natKmtx0RKda5+YX0tpky7rczkMSECJ+1vGYoir3nQh4cLGlkqUepNPP5lo/G7ZVPeTFXNgTFWWo9ec5fU/B5PZSz6A0LKgzHsPceWcvcJar9Xtn6vyBD3WdIokYuW868CXDs0gukQuHr+H4ENvLx3rFdlJV4nLVU90cKAMd9qBmVvqjOKJeGf9Lyykdr4Cgh0kacGtvs/bwFRxrQql+bvOigZlegHIeAwGMU3zo2rVFGKEX7mrtslkOf316IjfmEFi7RShiSG3HI/2U73aM8iXzC3cmw601aQpeZ3hvCdsIgc7DaISwJVSWkJL22R+J3a1oDJPTr3j6Sy7yltkKKJZYzGipjC5huWGVmhpUUHizglMb4/T4oxy3Zc67RdWOfVZlndp/0GmKA0M2W/FEUMUTxgaEOx4HVfEHt5hrJ+Lxrxmng0dI1UhvqD+hhkoyNBrpZ2txf1thWuy5HxylOmqB2XObOLl6rOsmR+BiO9BE02tStCegkZ3YlbEhtzWJuEhi6h4/yY=
  - secure: e/TZQNdvzvKeQB2esr1HWipxomoWf5X0Cz16xBxNbyMQ9hkfQhoLXcHX7tn2Ybziew/egkEg2SQf3NLRz9HYJNHbwTAlMgzDVSjxKoZjl60zAPULXnZyWou3kHW85PsgQHaAdG6CLjcv3a4bsaLhVDGvAxdnkMgUyAhKZ/snLkASwkElCp80NL6/JivX9TAwYZTf65ggOM5+vBWblDJBiySIfV7CVdHO5Unz2aoe/HwthSpHQ/8znd/In5MgE7TU9k6/a/vMY24bSbE0K5OjxVhslPww0IY4v+x7pgs2Ho+okc4OP9rXOLp2F1kOaz0r7rQANhriJRXAlcCYKJT0CcraCmPbl0IcNEtUO5zCUeUJ+fchtfFEj9lQXPzapJhgskOQYG/nwIG8c7089ADejeGF8qKW1he95Uer1+eHI9KSb66nxKvD2b2BVIdtWn++2jVr+5qeZWgR3fAyXIwVtAtZN7OqCCqECO7s0tp8Mo/SIUY++BmPShYfPelLjAWjV4isvoxHVuBQNDErgY9wD+M8tyj7roEpykeI2fjVKYg4lS5CAxvertBPf1hCg5yoPNl079M1jtNklJVL/wAo0ndsp4a3PTI2wMCK9cuvbWomNKB+pPvTGUE/UNvdAzR0Ii82tkBifpGaA+rxquTLIt1/6VZvBvmL3Q1bM9P3C/Y=
