language: node_js
sudo: false
node_js: '0.11'
before_install:
- npm install && npm install bower
- bower install
addons:
  sauce_connect: true
before_deploy: bash ./ci/build_release.sh
deploy:
- provider: releases
  api_key:
    secure: S1+ZPSMSsRP7IvG2dRx27R7f1tJMpTwNSIe2dayshfsXy2tRsLyZtO+xqFW+/j7OczVXmDyngHghl/CI/ykjsPrQDCBmbNRwrICIYPcrvb4d6F97aHbCkCv/j3+QyGtuceupF/2SooAVNwIo8M237VBfnZMBML53B5Pm0l/OO9wxA4VYuwrheyg9P0aRH01KAUwCP84p39ej/VMAsnAdmaK8slLioeuZy12pXQwfAVPRkzlzhCuecSkGexU4WLXl9HpoVCrsjPVhCQWuK9ZRdeAXIZAhB6c4GCGfpszmj459/jf68h7/1qPKz1bc2HzMTOvSE2C7mbp3G78qJl58boRKCEIJqBygLPAYcekRFFgbuqBlcA7pbfC5PO+cuLZASKETYXZEG8sqOsqo1MjGoKb23zjOreyX7w/yXGROLwRz/zXRkg00Kg8Wv4+M1y3OvGL6PXvy7nckFizsHZyYFgrLp0AQsEHfx0H0X2dmz3ZFS0bsK0tzh3gpClRQlx83259voMcpFBNCfU0F7zwmwkE0F+5NFHZk/D8zpEybEJ+4UkwY6CK7AjlFumeToDPaw8tQWlwdriH5cf0938Ouitu4a3K6QmXceIL+f/QFNMaUafmgXVOgDgw/+fdn8aFejSkMcf2ZVfrDs2d/Gl/0w8ehEnh/PNeIsKpsXhxrSO8=
  file:
  - dist.tar.gz
  - dist.zip
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: bash ./ci/update_pages.sh
  skip_cleanup: true
  on:
    branch: master
cache:
  directories:
  - node_modules
  - bower_components
env:
  global:
  - NODE_ENV=travis
  - secure: cxXlMlAfPqXPp9/874qfGCk9Dq42WbECJCiLjm3+p0nJKnBEOUIo8cObUC5bMKbY+Jsx227Yct6Z8V3nGW4/C+xqwPaiXzwSiylqPsuubnxq83VKoRa2Ycjk5jqMgAqhVXExpFI7TLAuKRVYxKRh5GjTapWwDdvvikMNtV6+tc2rErW4Tu1zG4FlwHuR+D+0iT3AfViLJQXk+OInWowuwsUFByYlp9foBy0RMlMSoBRfwAd4YV5A1HM2Wchz56/J4yxmAcmD11A566mqi3dOnsvgfNBTYJJA4xmlzTpwNdWwyUi5dCOy6BrvrXKBeVfE/nKC1yNC5kEd/5k0j1F0RHU6X4xZliLLIisxoTddrVjSYrOFYn+ynK6eHdFp0sg/K8Ab/BZCfMx28NemMa8QO4d6MH27An1thhVIj+ixV2x8j81Xjh+bsD9S0SFplXfGFZn4gY1V0M1k54X/yxKNwFXabilh8tQXypu49j526cos3MDDNYkZemx13cR8oTgbGRhIfoRthP7j2F8yA6PxJnyAyaMnZa0lU3qGjNQB6oD/NxNLf7eJ5SptKLcycoA31PiFEi7zjkEriXwOx2JKV6dVHU2RW+7yO8/YaMUnGz52y+h7i+TEZY+yBXxF6QRcoMSIypoeHYrctOxcO1T/iEYUSUs4w2CUqt2SrWvd2V0=
  - secure: GLhurlKQrMXS4z+NFQ3sZLcr+1+tQSKOMk/xVikGTComru+pyqW3ir+q+JAgQFvRgnQdQEVsZioQ+puzZb3tPFSPWOdFupiFYJ9tbamUJkXtge2XLRW7/K5Qn+u0ZRjqi9dDV6uCnWCeE34pKApUEvf4eek69Z7SiqHolT76vFMH0NV0kdRZehB/HZi/Fd2pDyFJlaoJiA2pmHVMuy7SINlmeMdEziQFpJ2hZbNe/2X2xQdGR6u/gBhOa+wQA6VDWQwXJCwc7VV84qQKx1hL0kVwmRMPvUL0h5W1R9zgMuzLKTWeTUfdWPMK4u0bOtKm/Et2BmF9rzE2YjStudcDv6lpazYpxITo747aD5+OwXyIT4RGKEXChScpgYDhxECMPUpjDBMAvaOEuynDJCTJiL1OfIAhzIwTAUBx+VqcFPsuwS6OYCxjy0xxSnywE0xeDynw1ApM/Mir4XtGuszNARrInnwXifaUJhXgUH/8dAHE+mslkb5cUKGFSYa6Q/Js2V6NfdUCK32SaYsm41CqYE9mMAwVSpseEZlBr5KN6xxmxoFgNXvo53Td2Ml1ly2Kxdhz3l4xl2kQWWu9XMqLi4NcDsjOSsijt7Wi8pRtji7PIjbpubw0H3q8Gg/PVl4xhzUQ0rhHdE+pNkfnjHpDKlXzAGP/Cgdz1bFwf6WlE10=
  - secure: MMa00Mi8rkHcJH8W6glwDDXcfP89xAyijPj15JDv4eKd5EqgJre7tZ2YqwhysUBu769+TdZJmHelQv7DwHmZxgi06nzFTSGAGJ8n4XwAoODTSu184ZCiGFGoa30SciZowFci9ssmRLB1+qYqNDXDGvdh9GEIO2ep18bfmEetB4Gq5mkdBZMZwdfuJGjtk2i/y2nCLnPpWlUefFS7bETu3TdeH/fhz7Y1VzDsFzTRb/59d4EwwIc08O3sHOJX3o42R+BqaxIyR5E+zI9Xz6YuVUpyuhcuq72dqvO64mSwmdZLvjys2YrvgxstfjjccoRcq4mi/HwyYo+auv1IEVmQE++5NrKyeJW15wwAIkYrd+YCWHijd8tTcGrQAfFgotVvPu3FC8/URHkkPuRLM4joBi4a9u6PVwyRoSrA6lXHcHXLGWLmkTdKqoOF+kHS+wIdFXwmSg7Jjeejt/X0DGihBqYic0oiw3SyI5oYKVhGmutjYtG2yXYtdHUGcXb5V/LAIU4wWi3OW4MSxRSgVhdSJl7CyCQUVDiu921rLtJI7gzcDrHEWoi2U7uUjF4cTVf3lKN93tlY6LJVZTIKBK8wqzKbrpDLlLzCo0xxC7sLc36sW+1PTVKDdI649673XCEOt/hcd20jQk+BnCwPqTQL886QQJtWiwmZZIEHbVEiJGQ=
